---
title: "HVO_DtxR_RTqPCR"
output: html_document
---
#This code analyzes RT-qPCR and ChIP-qPCR data for understanding the regulator network of DtxR TFs regulating iron response in _Hfx. volcanii_
```{r setup, include=FALSE}
# fresh start
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

## Set up environment
```{r}
library(plyr)
library (tidyverse)
library(readxl)
library(ggplot2)
library(rstatix)

```

## Load in qRT-PCR data analyzed
```{r}
#import data file
rt.raw <- read_excel("RT-qPCR-dtxR-alldata12122018-revApr2023.xlsx", sheet = "RT-qPCR-dtxR-alldata12122018-re")
rt.ratio <- read_excel("RT-qPCR-dtxR-alldata12122018-revApr2023.xlsx", sheet = "Dcq_results")
rt.recalc <- read_excel("RT-qPCR-MMP-20230517.xlsx", sheet = "RT-MMP-rearranged")

#calculate average and standard deviation of Ct values and efficiencies across biological replicates.
rt.stats <- plyr::ddply(rt.raw, c("strain", "gene...2", "condn"), summarise, mean.ct = mean (avg.techrep.ct), sd.ct = sd(avg.techrep.ct), sem.ct = (sd(avg.techrep.ct))/sqrt(3))

rt.recalc.stats <- plyr::ddply (rt.recalc, c("strain", "gene", "condn"), summarise, mean.effct = mean (eff.neg.d.cq), sd.effct = sd(eff.neg.d.cq), sem.effct = (sd(eff.neg.d.cq))/sqrt(3))

#make a table that contains mean efficiences for each primer set across all bioreps and strains
#rt.mean.effs<-plyr::ddply (rt, "gene", summarise, mean.eff = mean(eff), sd.eff = sd(eff))
#write.table (rt.mean.effs, file = "rt.mean.effs.txt",sep = "\t")
#use Pfaffl method to calculate relative expression ratio (mutant : WT) for each gene
#rer <- for (g in rt$gene){}
```

## Make graphs - -deltaCq
```{r}
cond.cols <- c(no.fe = "white", plus.fe = "grey40")
my.cols<-  c(pyrE="orangered4", d.idr = "seagreen",  d.sirR ="gold", d.troR ="deepskyblue")
rt.ratio %>% 
ggplot(aes(x = strain, y = `avg.-∆cq`, color = strain, fill = condn)) +
  xlab("strain") +
  ylab("negDeltaCq") +
  geom_point(stat = "identity", position = position_dodge(width = 0.9), shape = 21, size = 3) +
  geom_errorbar(aes(ymin = `avg.-∆cq` - sem, ymax = `avg.-∆cq` + sem),
    width = .1,
    size = 1, position = position_dodge(0.9)
  ) +
  facet_grid (.~gene) +
  
  #scale_fill_viridis("strain", discrete = TRUE, begin = 0.2, end = 0.8, direction = -1) +
  scale_fill_manual("Fe condition", values = cond.cols) +
  scale_color_manual("Strain", values = my.cols) +
 # scale_y_continuous(expand = expansion(mult = c(0, 0.02))) +
  theme_bw() +
  theme(
    axis.title.y = element_text(face = "plain", color = "#000000", size = 14, angle = 90),
    axis.text.y = element_text(face = "plain", color = "#000000", size = 12, angle = 0),
    axis.text.x = element_text(face = "plain", color = "#000000", size = 12, angle = 45, hjust = 1)
    
   # panel.grid.major = element_blank(), panel.grid.minor = element_blank()
  ) -> figure

#pdf( "rt-qpcr-plot.pdf", width = 6, height = 2.5)
plot(figure)
#dev.off()

```
## Stats tests - for each gene, is the difference between +/- Fe different in each strain? 
```{r}
#all by all t-test with BH correction for multiple hypothesis testing seems the best way to go given that I'm interested in all the comparisons. 
#first rename the columns because the ∆ symbol is causing problems
colnames(rt.ratio) <- c("strain", "gene", "condn", "avg.cq", "sd", "sem")

#combine the metadata such that all by all can take place (strain vs condition)
rt.comb <- unite (rt.ratio, ID, sep = "_", remove = TRUE)

#then separate those into different data frames by gene


 t<- pairwise_t_test(rt.ratio, avg.cq ~ gene,  p.adjust.method = "BH") 
t
write.csv (t, file = "troR-rtqpcr-stats.csv")
```

## Make graphs - -deltaCq without B0046
```{r}
cond.cols <- c(no.fe = "white", plus.fe = "grey40")
my.cols<-  c(pyrE="orangered4", d.idr = "seagreen",  d.sirR ="gold", d.troR ="deepskyblue")
rt.ratio %>% 
  filter (! gene == "HVO_B0046") %>%
ggplot(aes(x = strain, y = `avg.-∆cq`, color = strain, fill = condn)) +
  xlab("strain") +
  ylab("negDeltaCq") +
  geom_point(stat = "identity", position = position_dodge(width = 0.9), shape = 21, size = 3) +
  geom_errorbar(aes(ymin = `avg.-∆cq` - sem, ymax = `avg.-∆cq` + sem),
    width = .1,
    size = 1, position = position_dodge(0.9)
  ) +
  facet_grid (.~gene) +
  
  #scale_fill_viridis("strain", discrete = TRUE, begin = 0.2, end = 0.8, direction = -1) +
  scale_fill_manual("Fe condition", values = cond.cols) +
  scale_color_manual("Strain", values = my.cols) +
 # scale_y_continuous(expand = expansion(mult = c(0, 0.02))) +
  theme_bw() +
  theme(
    axis.title.y = element_text(face = "plain", color = "#000000", size = 14, angle = 90),
    axis.text.y = element_text(face = "plain", color = "#000000", size = 12, angle = 0),
    axis.text.x = element_text(face = "plain", color = "#000000", size = 12, angle = 45, hjust = 1)
    
   # panel.grid.major = element_blank(), panel.grid.minor = element_blank()
  ) -> figure

pdf( "rt-qpcr-plot-noB0046.pdf", width = 6, height = 2.5)
plot(figure)
dev.off()

```

## Make graphs - -deltaCq  B0046 only
```{r}
cond.cols <- c(no.fe = "white", plus.fe = "grey40")
my.cols<-  c(pyrE="orangered4", d.idr = "seagreen",  d.sirR ="gold", d.troR ="deepskyblue")
rt.ratio %>% 
  filter ( gene == "HVO_B0046") %>%
ggplot(aes(x = strain, y = `avg.-∆cq`, color = strain, fill = condn)) +
  xlab("strain") +
  ylab("negDeltaCq") +
  geom_point(stat = "identity", position = position_dodge(width = 0.9), shape = 21, size = 3) +
  geom_errorbar(aes(ymin = `avg.-∆cq` - sem, ymax = `avg.-∆cq` + sem),
    width = .1,
    size = 1, position = position_dodge(0.9)
  ) +
  facet_grid (.~gene) +
  
  #scale_fill_viridis("strain", discrete = TRUE, begin = 0.2, end = 0.8, direction = -1) +
  scale_fill_manual("Fe condition", values = cond.cols) +
  scale_color_manual("Strain", values = my.cols) +
 # scale_y_continuous(expand = expansion(mult = c(0, 0.02))) +
  theme_bw() +
  theme(
    axis.title.y = element_text(face = "plain", color = "#000000", size = 14, angle = 90),
    axis.text.y = element_text(face = "plain", color = "#000000", size = 12, angle = 0),
    axis.text.x = element_text(face = "plain", color = "#000000", size = 12, angle = 45, hjust = 1)
    
   # panel.grid.major = element_blank(), panel.grid.minor = element_blank()
  ) -> figure0046

pdf( "rt-qpcr-plot-B0046only.pdf", width = 4, height = 4)
plot(figure0046)
dev.off()

```
